server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atsujv.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 101215
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloudHystrix
    prefer-ip-address: true  #注册的名字鼠标点上去显示真正的ip
info:
  app.name: atsujv-microservicecloud
  companyname: zhangsujv
  build.artifactId: microservicecloud-provider-dept-hystrix
  build.version: 1.0-SNAPSHOT